"""Add Guest table

Revision ID: 20bfc76ecc60
Revises: 319fba43d83c
Create Date: 2025-08-06 19:54:56.330429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bfc76ecc60'
down_revision: Union[str, None] = '319fba43d83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noc_application',
    sa.Column('tracking_number', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('tracking_number')
    )
    op.create_table('guest',
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('tracking_number', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracking_number'], ['noc_application.tracking_number'], ),
    sa.PrimaryKeyConstraint('guest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    op.drop_table('noc_application')
    # ### end Alembic commands ###
