"""Fix 1:1 relationship between Guest and NOCApplication

Revision ID: 8884ff7d049d
Revises: 
Create Date: 2025-08-08 20:20:50.808559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8884ff7d049d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noc_application',
    sa.Column('tracking_number', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('burial_location', sa.String(length=100), nullable=True),
    sa.Column('documents_uploaded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('tracking_number'),
    sa.UniqueConstraint('guest_id')
    )
    op.create_index(op.f('ix_noc_application_tracking_number'), 'noc_application', ['tracking_number'], unique=False)
    op.drop_constraint(op.f('service_types_slug_key'), 'service_types', type_='unique')
    op.create_index(op.f('ix_service_types_slug'), 'service_types', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_types_slug'), table_name='service_types')
    op.create_unique_constraint(op.f('service_types_slug_key'), 'service_types', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_noc_application_tracking_number'), table_name='noc_application')
    op.drop_table('noc_application')
    op.drop_table('guest')
    # ### end Alembic commands ###
