"""Make tracking_number nullable in guest

Revision ID: 947917ac78ef
Revises: 20bfc76ecc60
Create Date: 2025-08-06 21:01:57.708500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947917ac78ef'
down_revision: Union[str, None] = '20bfc76ecc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest', 'tracking_number',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest', 'tracking_number',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
