"""Adding relationshipsss

Revision ID: 953f2a822bde
Revises: a8d2ddad3578
Create Date: 2025-08-10 17:21:44.176122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "953f2a822bde"
down_revision: Union[str, None] = "a8d2ddad3578"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("noc_application", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "noc_application", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "noc_application", type_="foreignkey")
    op.drop_column("noc_application", "user_id")
    # ### end Alembic commands ###
