"""Removing Slug column and changing lengths of attributes

Revision ID: 9e29655509e1
Revises: 953f2a822bde
Create Date: 2025-08-17 14:27:17.555823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e29655509e1"
down_revision: Union[str, None] = "953f2a822bde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_types",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=250),
        existing_nullable=False,
    )
    op.alter_column(
        "service_types",
        "description",
        existing_type=sa.TEXT(),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_service_types_slug"), table_name="service_types")
    op.create_index(op.f("ix_service_types_id"), "service_types", ["id"], unique=False)
    op.drop_column("service_types", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_types",
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )

    op.drop_index(op.f("ix_service_types_id"), table_name="service_types")
    op.create_index(
        op.f("ix_service_types_slug"), "service_types", ["slug"], unique=True
    )
    op.alter_column(
        "service_types",
        "description",
        existing_type=sa.String(length=2000),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "service_types",
        "name",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
