"""Tracking Application Table

Revision ID: dbc12b012782
Revises: 8884ff7d049d
Create Date: 2025-08-09 15:25:24.630213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc12b012782'
down_revision: Union[str, None] = '8884ff7d049d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('noc_tracking_number', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('is_guest_application', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['noc_tracking_number'], ['noc_application.tracking_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id'),
    sa.UniqueConstraint('noc_tracking_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_application')
    # ### end Alembic commands ###
